USE MOVIES;

CREATE VIEW MOVIE_INFO AS
SELECT DISTINCT TITLE, DIRECTOR.FNAME AS DIRECTOR_FNAME, DIRECTOR.LNAME AS DIRECTOR_LNAME,
	ACTOR.FNAME AS ACTOR_FNAME, ACTOR.LNAME AS ACTOR_LNAME 
    FROM MOVIE, DIRECTOR, ACTOR, LEAD_ROLE
WHERE MOVIE.MOVIE_CODE=LEAD_ROLE.MOVIE_CODE AND LEAD_ROLE.ACTOR_CODE=ACTOR.ACTOR_CODE 
	AND MOVIE.DIRECTOR_CODE=DIRECTOR.DIRECTOR_CODE;

CREATE VIEW ACTORS_IN_MOVIE AS
SELECT TITLE, ACTOR.FNAME, ACTOR.LNAME FROM MOVIE, PERFORMS_IN, ACTOR
WHERE ACTOR.ACTOR_CODE=PERFORMS_IN.ACTOR_CODE AND PERFORMS_IN.MOVIE_CODE=MOVIE.MOVIE_CODE;

CREATE VIEW PRODUCERS_IN_MOVIE AS
SELECT TITLE, PRODUCER.FNAME, PRODUCER.LNAME FROM PRODUCER, PRODUCES, MOVIE
WHERE PRODUCER.PRODUCER_CODE=PRODUCES.PRODUCER_CODE AND PRODUCES.MOVIE_CODE=MOVIE.MOVIE_CODE;

CREATE VIEW ACTOR_DIRECTOR AS
SELECT ACTOR.FNAME, ACTOR.LNAME FROM ACTOR, DIRECTOR
WHERE DIRECTOR.ACTOR_CODE=ACTOR.ACTOR_CODE;

CREATE VIEW ACTOR_PRODUCER AS
SELECT ACTOR.FNAME, ACTOR.LNAME FROM ACTOR, PRODUCER
WHERE PRODUCER.ACTOR_CODE=ACTOR.ACTOR_CODE;

